### ISSUE TITLE
Is Kafka supported through `taskiq-aio-kafka`?

### ISSUE THREAD

**Issue by MuriloScarpaSitonio** [taskiq-python/taskiq#147]
I have found [this](https://pypi.org/project/taskiq-aio-kafka/) PyPI package (code can be found [here](https://github.com/taskiq-python/taskiq-aio-kafka)) searching in Google but I wasn't able to find any citation in the documentation. Can this be considered stable and something supported by the `taskiq` team?!

**Comment by s3rius** [comment]
Yes. You can ping @chandr-andr for any questions.

**Comment by s3rius** [comment]
If the problem is resolved, don't forget to close the issue. 

If you find your experience with [taskiq](https://github.com/taskiq-python/taskiq) pleasant, you can help us improve, by hitting the star button, giving us feedback here in the [discussion](https://github.com/orgs/taskiq-python/discussions/69) or becoming a [sponsor](https://github.com/sponsors/taskiq-python) (Github will give you a cool sponsor emblem on your profile).

**Comment by MuriloScarpaSitonio** [comment]
Thank you for the confirmation! One thing that it's not directly related with kafka is an example to use `taskiq` as a consumer. I imagine I have to use the `broker.listen` method somehow but I haven't found an example. Are you aware of an example that shows this behavior?

**Comment by s3rius** [comment]
Why should you use listen directly?  Can you provide more details on what you want to accomplish?

**Comment by MuriloScarpaSitonio** [comment]
I want to process a message from a given topic. Those messages would be produced by another system and my system would simple consume them as they arrive in the topic. So essentially I want to "listen" and process all new messages from this topic. What would you advise?

**Comment by s3rius** [comment]
Take a look at [receiver](https://github.com/taskiq-python/taskiq/blob/3f8af4563128b5597d797d0dd29dee2863a74236/taskiq/receiver/receiver.py#L39). It uses broker to read incoming messages and processes them.
