### ISSUE TITLE
Add --factory command line parameter

### ISSUE THREAD

**Issue by realitix** [taskiq-python/taskiq#292]
Hello,
Currently, when starting a worker, we have to pass a broker instance directly in the CLI.
It would be good to allow a factory function like with uvicorn.

Thanks

**Comment by s3rius** [comment]
Hi. I was thinking about this one. I can add it, but it actually makes no sense to me, since tasks have to be assigned to broker. If your broker is going to be created in the function, you won't be able to call a `task` function on it.

I would be interested in how are your going to use. Can you please share your thoughts?
