### ISSUE TITLE
Set the task name as task_id

### ISSUE THREAD

**Issue by realitix** [taskiq-python/taskiq#361]
Hello and thank you for Taskiq, which is really well made.

Would it be possible to add the task_id as the task name? This would make it easier to retrieve the task ID directly from the task itself. I use this feature to capture all logs associated with a task using Loguru, and I rely on the task name for that. Then, I associate it with the task_id from Taskiq.

Thanks

**Comment by s3rius** [comment]
Thanks for your words. I don't think it is possible, because task names are used for function resolving which function to run. Although if you just want to get the task id from inside the task, then you can easily use context for that purpose. As far as I understood the problem, it should be enough. 

https://taskiq-python.github.io/guide/architecture-overview.html#context
